### ISSUE TITLE
I can view EDID contents by Monitor Asset Manager in Windows but can’t view in Ubuntu 

### ISSUE THREAD

**Issue by qbzhhh** [bulletmark/edid-rw#14] opened 2020-07-22 23:04 UTC
It says version 105 problem, just like another issue posted years ago. The version of my Monitor is 1.3
Can anyone help?

**Comment by bulletmark** [comment] 2020-07-22 23:20
What says "version 105 problem"? Please paste the exact command you are typing with the exact error message response.

**Comment by qbzhhh** [comment] 2020-07-22 23:51
sudo ./edit-rw 0 | edid-decode

Error: unknown edid version 105
Edid extract of ‘stdin’ failed

**Comment by qbzhhh** [comment] 2020-07-22 23:54
After added print(edidhdr) after line 59, the output shows: [146,19,11,3,4,33,2,9,3,82,1,8,10,0,254,0,105,120,105,48]

**Comment by qbzhhh** [comment] 2020-07-23 00:02
![image](https://user-images.githubusercontent.com/48610488/88240771-b7ed7f80-ccba-11ea-9d66-f500f2e2579e.jpeg)

Edid information from Monitor asset manager

**Comment by bulletmark** [comment] 2020-07-23 00:03
edid-decode is the program reporting the error 105. What are you reporting that issue here?

**Comment by qbzhhh** [comment] 2020-07-23 00:08
The script cannot read the EDID info correctly, how can I modify the script and rewrite the monitor's EDID data?

**Comment by bulletmark** [comment] 2020-07-23 00:17
Note sure why you raised a new bug when this is a duplicate of issue #10. This is an extremely simple noddy program I wrote very many years ago for my own one-off use. Feel free to debug it for you use case and raise a PR.

**Closed by bulletmark** 2020-07-23 00:17 UTC
Labels: duplicate
